name: Az óriás ölelése
favicon: null
layout_spectrum: 0.67947
typography_spectrum: 0.74278
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8aaf2c'
    - '#5e7b1e'
    - '#a1bf56'
    - '#e8efd5'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
